services:
  - type: web
    name: employee-registry-api
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d6pbril6ubrc73dpre40-a.singapore-postgres.render.com;Port=5432;Database=employee_registry_db_3ad7;Username=employee_registry_db_3ad7_user;Password=e8gdgiNNXMy4IL7M8aH0YLyvQpaF6ZZn;SSL Mode=Require;Trust Server Certificate=true
      - key: Jwt__Secret
        generateValue: true
      - key: AllowedOrigins
        value: "*"

databases:
  - name: employee-registry-db
    plan: free
