// <auto-generated />
using System;
using EmployeeRegistry.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeRegistry.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312111627_InitialPostgreSQLMigration")]
    partial class InitialPostgreSQLMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeRegistry.Models.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2015, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Name = "Ayan Islam"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2018, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Name = "Sara Islam"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2016, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            Name = "Rayhan Uddin"
                        });
                });

            modelBuilder.Entity("EmployeeRegistry.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NID")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasicSalary = 50000m,
                            Department = "IT",
                            NID = "1234567890",
                            Name = "Tanvir Islam",
                            PhoneNumber = "01712345678"
                        },
                        new
                        {
                            Id = 2,
                            BasicSalary = 45000m,
                            Department = "HR",
                            NID = "1234567891",
                            Name = "Rahim Uddin",
                            PhoneNumber = "01812345679"
                        },
                        new
                        {
                            Id = 3,
                            BasicSalary = 48000m,
                            Department = "Finance",
                            NID = "1234567892",
                            Name = "Karim Ahmed",
                            PhoneNumber = "01912345680"
                        },
                        new
                        {
                            Id = 4,
                            BasicSalary = 52000m,
                            Department = "IT",
                            NID = "1234567893",
                            Name = "Sadia Afrin",
                            PhoneNumber = "01512345681"
                        },
                        new
                        {
                            Id = 5,
                            BasicSalary = 42000m,
                            Department = "Marketing",
                            NID = "1234567894",
                            Name = "Nusrat Jahan",
                            PhoneNumber = "01612345682"
                        },
                        new
                        {
                            Id = 6,
                            BasicSalary = 40000m,
                            Department = "Sales",
                            NID = "1234567895",
                            Name = "Abul Kashem",
                            PhoneNumber = "01312345683"
                        },
                        new
                        {
                            Id = 7,
                            BasicSalary = 46000m,
                            Department = "HR",
                            NID = "1234567896",
                            Name = "Fatima Zohra",
                            PhoneNumber = "01412345684"
                        },
                        new
                        {
                            Id = 8,
                            BasicSalary = 47000m,
                            Department = "Operations",
                            NID = "1234567897",
                            Name = "Kamal Hossain",
                            PhoneNumber = "01712345685"
                        },
                        new
                        {
                            Id = 9,
                            BasicSalary = 51000m,
                            Department = "IT",
                            NID = "1234567898",
                            Name = "Mitu Akter",
                            PhoneNumber = "01812345686"
                        },
                        new
                        {
                            Id = 10,
                            BasicSalary = 44000m,
                            Department = "Admin",
                            NID = "1234567899",
                            Name = "Zahid Hasan",
                            PhoneNumber = "01912345687"
                        });
                });

            modelBuilder.Entity("EmployeeRegistry.Models.Spouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("NID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Spouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            NID = "9876543210",
                            Name = "Farhana Yasmin"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            NID = "9876543211",
                            Name = "Sumaiya Akter"
                        });
                });

            modelBuilder.Entity("EmployeeRegistry.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$0J3fwrgyUWx.3IU0stZ.ouvA5Tu1HBGnkOO.wtdORK293jTzFhATu",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$.CiIqxneksNMGkWRiLEeceTWOnjZ8UQ5rJqd16C9Uito9aesQeFJe",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EmployeeRegistry.Models.Child", b =>
                {
                    b.HasOne("EmployeeRegistry.Models.Employee", "Employee")
                        .WithMany("Children")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeRegistry.Models.Spouse", b =>
                {
                    b.HasOne("EmployeeRegistry.Models.Employee", "Employee")
                        .WithOne("Spouse")
                        .HasForeignKey("EmployeeRegistry.Models.Spouse", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeRegistry.Models.Employee", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Spouse");
                });
#pragma warning restore 612, 618
        }
    }
}
